### ISSUE TITLE
Use trim() after parsing the xml data to ensure  that no whitespaces appeared after the conversion from json to xml

### ISSUE THREAD

**Issue by 9SphynX9** [r0bn/swp2#46]

**Comment by thisisdanny** [comment]
from json to xml? we never convert from json to xml?! we receive the xml as string inside a json object.

do we have to use trim? or is preg_replace maybe better for the job? we don't know... please tell us more what your tests in php 5.4.16 came up with since you're providing specific functions we should implement.
