### ISSUE TITLE
get wrong http status code

### ISSUE THREAD

**Issue by huth1** [r0bn/swp2#90]
For following xml, the server return http status code 200.
But "http://api.storytellar.de/docs/tests/xmlschemavalidation" says, that the xml is not valid.
Also the story isn't updated.

**Comment by huth1** [comment]
![xml](https://cloud.githubusercontent.com/assets/11649772/8191433/4d2750aa-1468-11e5-85e3-a6ed3ce60e6d.jpg)

**Comment by thisisdanny** [comment]
You have to provide an ID.

And if the story is not tagged as final we don't care if it's valid or not.

And what do you mean with not updated?

**Comment by huth1** [comment]
ID = 44
the story was tagged as final, but not saved as final

**Comment by huth1** [comment]
Stories without a storypoint are accepted as final story, but not saved as final story.

**Comment by thisisdanny** [comment]
This is the expected behavior!

The server only stores valid stories as final. If the front-end checkbox "final" has no function (except sending a final parameter) then you should consider opening a ticket for what you really want - a xml validation in the editor.

We even joked last time that we could just dismiss an invalid story that is tagged as final, but we are so kind to have a fallback with our open pool of stories. So I'm not quite sure why you're opening this ticket for us.

Btw, you can copy and paste code here, screenshots are lame for that.
